modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/ZeithComms/Telebeacons/issues"
license="All rights reserved"
[[mods]]
modId="telebeacons"
version="${file.jarVersion}"
displayName="Telebeacons"
updateJSONURL="http://dccg.herokuapp.com/api/fmluc/506427"
displayURL="http://dccg.herokuapp.com/api/fmlhp/506427"
credits="Violet for commissioning the mod!" #optional
authors="Zeitheron" #optional
description='''
Beacon-based teleportation network in Minecraft!
'''
[[dependencies.telebeacons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE" # NONE/BEFORE/AFTER
    side="BOTH"
[[dependencies.telebeacons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.telebeacons]]
    modId="hammerlib"
    mandatory=true
    versionRange="[16.3,)"
    ordering="NONE"
    side="BOTH"
